#ifndef __PRIMITIVE__
#define __PRIMITIVE__

#define   STACK_SIZE      32
struct    STACK{
  short       depth;
  STACK_ITEM  body[STACK_SIZE];
};
/*
 * 予約語の定義。
 * プリフィクスは、PWがプリミティブワード、PWIはプリミティブワードでイミディエイト、 
 * CWはコンパイラが暗黙に生成するコンパイリングワード。
 */
#define PW_DUP              "DUP"
#define PW_SWAP             "SWAP"
#define PW_DROP             "DROP"
#define PW_PICK             "PICK"
#define PW_OVER             "OVER"
#define PW_2DUP             "2DUP"
#define PW_DDUP             "DDUP"
#define PW_QDUP             "?DUP"
#define PW_ROLL             "ROLL"
#define PW_ROT              "ROT"
#define PW_RTOD             "R>"
#define PW_DTOR             ">R"
#define PW_RDROP            "RDROP"
#define PW_DEPTH            "DEPTH"
  // アトリビュートの変換と確認
#define PW_ATTR_INT         "INT"
#define PW_ATTR_FLOAT       "FLOAT"
#define PW_ATTR_STRING      "STRING"
#define PW_ATTR_CHAR        "CHAR"
#define PW_ATTR_INTQ        "INT?"
#define PW_ATTR_FLOATQ      "FLOAT?"
#define PW_ATTR_STRINGQ     "STRING?"
#define PW_ATTR_CHARQ       "CHAR?"
  // 算術演算系
#define PW_ADD              "+"
#define PW_SUB              "-"
#define PW_INC              "1+"
#define PW_DEC              "1-" 
#define PW_DIV              "/"
#define PW_DIVMOD           "/MOD"
#define PW_MUL              "*"
#define PW_EQUAL            "="
#define PW_NOTEQUAL         "!="
#define PW_GREATER          ">"
#define PW_SMALLER          "<"
#define PW_EQUALZERO        "0="
#define PW_GREATERZERO      "0>"
#define PW_SMALLERZERO      "0<"
  // 論理およびビット演算系
#define PW_AND              "&"
#define PW_OR               "|"
#define PW_XOR              "^"
#define PW_NOT              "~"
#define PW_SHR              ">>"
#define PW_SHL              "<<"
  // 数学関数（三角関数）系
#define PW_MIN              "MIN"
#define PW_MAX              "MAX"
#define PW_ABS              "ABS"
#define PW_CONSTRAIN        "CONSTRAIN"
#define PW_MAP              "MAP"
#define PW_POW              "POW"
#define PW_SQRT             "SQRT"
#define PW_SIN              "SIN"
#define PW_COS              "COS"
#define PW_TAN              "TAN"
#define PW_RADTODEG         "RADTODEG"
#define PW_DEGTORAD         "DEGTORAD"
  // 表示系
#define PW_H8               "H8"
#define PW_H16              "H16"
#define PW_H32              "H32"
#define PW_DICTFREE         "DICTFREE"
#define PW_PRINT            "."
#define PW_PRINTCHAR        "C."
#define PW_PRINTCHARVISIBLE "C.?"
#define PW_CRLF             "CRLF"
#define PW_PRINTCRLF        ".CRLF"
#define PW_PRINTH8          "H.8"
#define PW_PRINTH16         "H.16"
#define PW_PRINTH32         "H.32"
  // 制御構文などコンパイル中に特殊なコードが生成されるワード群
#define PW_HALT             "HALT"
#define CW_PUSHIP           "$$PUSHIP"
#define CW_POPIP            "$$POPIP"
#define CW_PUSHINT          "$$PUSHINT"
#define CW_PUSHFLOAT        "$$PUSHFLOAT"
#define PW_HELLO            "HELLO"
#define PWI_DO              "DO"
#define CW_DO               "$$DO"
#define PWI_LOOP            "LOOP"
#define CW_LOOP             "$$LOOP"
#define PWI_PLOOP           "+LOOP"
#define CW_PLOOP            "$$+LOOP"
#define PW_LEAVE            "LEAVE"
#define PW_RREAD            "R@"
#define PW_J                "J"
#define PW_I                "I"
#define CW_PUSHSTRING       "$$PUSHSTRING"
#define PWI_IF              "IF"
#define CW_JUMP             "$$JUMP"
#define PWI_FIF             "-IF"
#define CW_IFJUMP           "$$IFJUMP"
#define PWI_ELSE            "ELSE"
#define CW_FIFJUMP          "$$-IFJUMP"
#define PWI_THEN            "THEN"
#define PW_EXIT             "EXIT"
#define PWI_BEGIN           "BEGIN"
#define PWI_UNTIL           "UNTIL"
#define PWI_WHILE           "WHILE"
#define PWI_REPEAT          "REPEAT"
  // 定数群
#define PW_M10              "-10"
#define PW_M3               "-3"
#define PW_M2               "-2"
#define PW_M1               "-1"
#define PW_0                "0"
#define PW_1                "1"
#define PW_2                "2"
#define PW_3                "3"
#define PW_10               "10"
#define PW_TRUE             "TRUE"
#define PW_FALSE            "FALSE"
#define PW_INPUT            "INPUT"
#define PW_OUTPUT           "OUTPUT"
#define PW_INPUT_PULLUP     "INPUT_PULLUP"
#define PW_HIGH             "HIGH"
#define PW_LOW              "LOW"
#define PW_NULL             "NULL"
#define PW_A0               "A0"
#define PW_A1               "A1"
#define PW_A2               "A2"
#define PW_A3               "A3"
#define PW_A4               "A4"
#define PW_A5               "A5"
#define PW_A6               "A6"
#define PW_A7               "A7"
#define PW_A8               "A8"
#define PW_A9               "A9"
#define PW_M7_RAM1          "M7_RAM1"         
#define PW_M7_RAM2          "M7_RAM2"
  // Arduino関数群
#define PW_DELAY            "DELAY"
#define PW_PINMODE          "PINMODE"
#define PW_DIGITALWRITE     "DIGITALWRITE"
#define PW_DIGITALREAD      "DIGITALREAD"
#define PW_ANALOGWRITE      "ANALOGWRITE"
#define PW_ANALOGREAD       "ANALOGREAD"
#define PW_MILLIS           "MILLIS"
#define PW_RANDOMSEED       "RANDOMSEED"
#define PW_RANDOM           "RANDOM"
#define PW_TONE             "TONE"
#define PW_TONED            "TONED"
#define PW_NOTONE           "NOTONE"
  // ワード定義の開始と終了。
#define PWI_COLON           ":"
#define PWI_SEMICOLON       ";"
#define PW_DUMPON           "DUMPON"
#define PW_DUMPOFF          "DUMPOFF"
  // 変数のためのワード群。
#define PW_SYSSTRCLR        "SYS.STRING.CLEAR"
#define PW_SYSARYCLR        "SYS.ARRAY.CLEAR"
#define PW_SYSSTKCLR        "SYS.STACK.CLEAR"
#define PWI_VAR             "<VAR>"
#define CW_VAR              "$$VAR"
#define PW_VARREAD          "V@"
#define PW_VARWRITE         "V!"
#define PW_VARADDWRITE      "V+!"
#define PW_VARARRAYTOP      "V[]"
#define PW_VARARRAYREAD     "V[]@"
#define PW_VARARRAYWRITE    "V[]!"
#define PW_VARARRAYAPPEND   "V[]+"
#define PW_VARARRAYCLEAR    "V[]#"
#define PW_VARARRAYCOUNT    "V[]?"
#define PW_VARARRAYBTOP     "V[B]"
#define PW_VARARRAYBREAD    "V[B]@"
#define PW_VARARRAYBWRITE   "V[B]!"
#define PW_VARARRAYBAPPEND  "V[B]+"
#define PW_VARARRAYBCLEAR   "V[B]#"
#define PW_VARARRAYBCOUNT   "V[B]?"
  // maxim 1-Wire用ライブラリOneWireを使うためのワード群
#define PW_OW_BEGIN         "ONEWIRE.BEGIN"
#define PW_OW_RESET         "ONEWIRE.RESET"
#define PW_OW_SELECT        "ONEWIRE.SELECT"
#define PW_OW_SKIP          "ONEWIRE.SKIP"
#define PW_OW_WRITE         "ONEWIRE.WRITE"
#define PW_OW_WRITEBYTES    "ONEWIRE.WRITEBYTES"
#define PW_OW_WRITEBIT      "ONEWIRE.WRITEBIT"
#define PW_OW_READ          "ONEWIRE.READ"
#define PW_OW_READBYTES     "ONEWIRE.READBYTES"
#define PW_OW_READBIT       "ONEWIRE.READBIT"
#define PW_OW_RESETSEARCH   "ONEWIRE.RESETSEARCH"
#define PW_OW_TARGETSEARCH  "ONEWIRE.TARGETSEARCH"
#define PW_OW_SEARCH        "ONEWIRE.SEARCH"
#define PW_OW_CRC8          "ONEWIRE.CRC8"
  // メモリアクセスと文字列のためのワード群
#define PW_MEMREAD          "@"
#define PW_MEMWRITE         "!"
#define PW_MEMREADW         "W@"
#define PW_MEMWRITEW        "W!"
#define PW_MEMREADB         "B@"
#define PW_MEMWRITEB        "B!"
  // 動的メモリ管理と文字列操作のためのワード群
/*
#define PW_MEMALLOC         "MEMALLOC"
#define PW_MEMREALLOC       "MEMREALLOC"
#define PW_MEMFREE          "MEMFREE"
#define PW_STRCOPY          "STRCOPY"
#define PW_STRCAT           "STRCAT"
#define PW_STRCATC          "STRCATC"
#define PW_STRLENGTH        "STRLENGTH"
*/
  // シリアルイベント関連のワード群
#define PW_SERIALEVENT      "SERIALEVENT"
#define PW_SERIALLENGTH     "SERIALLENGTH"
#define PW_SERIALCHAR       "SERIALCHAR"
  // 辞書関連のワード群
#define PW_FIND             "FIND"
#define PW_FORGET           "FORGET"
#define PW_WORDS            "WORDS"
#define PW_USAGE            "USAGE"
#define PW_UPDATEUSAGE      "UPDATEUSAGE"
  //
void        initPrimitive();
void        initAllStacks();
int         getDStackLevel();
int         getRStackLevel();
int         getSStackLevel();
STACK_ITEM  popSStack();

const char **  initialWord();

#endif
